name: iOS and Windows Release Workflow

on:
  push:
    tags:
      - 'v*' # Trigger this workflow for tags starting with 'v' (e.g., v1.0, v2.1, etc.)

jobs:
  build_ios:
    runs-on: macos-latest  # Use macOS runner for iOS builds

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Step 3: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Install CocoaPods dependencies for iOS
      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      # Step 5: Build the iOS app
      - name: Build iOS
        run: flutter build ios --release --no-codesign  # Building without code signing

      # Optionally, Step 6: Archive iOS build artifacts
      - name: Archive iOS build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/  # Adjust this path if needed

  build_windows:
    runs-on: windows-latest  # Use Windows runner for Windows builds

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Step 3: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build the Windows app
      - name: Build Windows
        run: flutter build windows --release

      # Optionally, Step 5: Archive Windows build artifacts
      - name: Archive Windows build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/  # Adjust this path if needed